export const UPCOMING_MOVIES_FAILED = 'UPCOMING_MOVIES_FAILED';
export const UPCOMING_MOVIES_REQUESTED = 'UPCOMING_MOVIES_REQUESTED';
export const UPCOMING_MOVIES_SUCCEEDED = 'UPCOMING_MOVIES_SUCCEEDED';

export const GET_CONFIG_FAILED = 'GET_CONFIG_FAILED';
export const GET_CONFIG_REQUESTED = 'GET_CONFIG_REQUESTED';
export const GET_CONFIG_SUCCEEDED = 'GET_CONFIG_SUCCEEDED';