export const UPCOMING_MOVIES_FAILED = 'UPCOMING_MOVIES_FAILED';
export const UPCOMING_MOVIES_REQUESTED = 'UPCOMING_MOVIES_REQUESTED';
export const UPCOMING_MOVIES_SUCCEEDED = 'UPCOMING_MOVIES_SUCCEEDED';

export const GET_CONFIG_FAILED = 'GET_CONFIG_FAILED';
export const GET_CONFIG_REQUESTED = 'GET_CONFIG_REQUESTED';
export const GET_CONFIG_SUCCEEDED = 'GET_CONFIG_SUCCEEDED';

export const GET_GENRES_FAILED = 'GET_GENRES_FAILED';
export const GET_GENRES_REQUESTED = 'GET_GENRES__REQUESTED';
export const GET_GENRES_SUCCEEDED = 'GET_GENRES_SUCCEEDED';

export const ADD_TO_WATCHLIST_FAILED = 'ADD_TO_WATCHLIST_FAILED';
export const ADD_TO_WATCHLIST_REQUESTED = 'ADD_TO_WATCHLIST_REQUESTED';
export const ADD_TO_WATCHLIST_SUCCEEDED = 'ADD_TO_WATCHLIST_SUCCEEDED';

export const REMOVE_FROM_WATCHLIST_FAILED = 'REMOVE_FROM_WATCHLIST_FAILED';
export const REMOVE_FROM_WATCHLIST_REQUESTED = 'REMOVE_FROM_WATCHLIST_REQUESTED';
export const REMOVE_FROM_WATCHLIST_SUCCEEDED = 'REMOVE_FROM_WATCHLIST_SUCCEEDED';